/**
 * Typed registry of every RFC 7807 `extensions.code` the backend can emit.
 *
 * Source epic: Epic 1.3 — RFC 7807 Error Model.
 * Source ticket: TKT-1.3.3.1.
 *
 * ─── Source of truth ──────────────────────────────────────────────────────
 *
 * Every code in `ErrorCode` mirrors a key in
 * `quiz_backend/src/common/errors/problem-code-mapping.ts`. The 10
 * synthesized `GLOBAL_*` codes mirror the `STATUS_TO_GLOBAL_CODE` table
 * plus the `GLOBAL_VALIDATION_FAILED` override in
 * `quiz_backend/src/common/filters/global-exception.filter.ts` (§6.3,
 * §8.5 of the RFC 7807 migration plan).
 *
 * Total: 122 domain codes + 10 synthesized = 132 members.
 *
 * ─── How to regenerate ───────────────────────────────────────────────────
 *
 * When the backend adds a new domain exception:
 *
 *   1. Add the key to `ProblemCodeMapping` in `problem-code-mapping.ts`.
 *   2. Add the matching union member + array entry below (grouped by
 *      module prefix).
 *   3. Update any i18n map that branches on the new code (Phase 2+).
 *
 * The Phase-5+ plan is to generate this file from a CI job that
 * diffs `problem-code-mapping.ts` against the current `ErrorCode` and
 * files a follow-up issue when drift is detected.
 *
 * ─── Architecture gap ────────────────────────────────────────────────────
 *
 * The parent epic (TKT-1.3.3.2 of `EPIC_1_3_TICKETS.md`) references
 * `docs/architecture/standards/error-handling.md` as a secondary
 * source. That file does NOT exist at planning time — the integration
 * master plan references it as a target document, but it has not yet
 * been authored. The codes listed below are sourced directly from the
 * backend's `ProblemCodeMapping` and `STATUS_TO_GLOBAL_CODE` instead.
 * When the architecture doc lands, this header should be updated.
 *
 * ─── Why this file exists ────────────────────────────────────────────────
 *
 * Without a typed registry, callers have to branch on raw HTTP status
 * (`apiError.status === 404`) which is too coarse: multiple domain
 * codes map to the same status. With `ErrorCode`, callers can write:
 *
 *   if (apiError.code === 'QUIZ_NOT_FOUND') { ... }
 *
 * and TypeScript will flag typos at compile time.
 */

export type ErrorCode =
  /** ACHIEVEMENT module — 2 codes */
  | 'ACHIEVEMENT_USER_NOT_FOUND'
  | 'ACHIEVEMENT_GRANT_ERROR'
  /** ATTEMPT module — 10 codes */
  | 'ATTEMPT_NOT_FOUND'
  | 'ATTEMPT_FORBIDDEN'
  | 'ATTEMPT_VALIDATION_FAILED'
  | 'ATTEMPT_ALREADY_STARTED'
  | 'ATTEMPT_NOT_ACTIVE'
  | 'ATTEMPT_QUESTION_ALREADY_ANSWERED'
  | 'ATTEMPT_QUIZ_NOT_PUBLISHED'
  | 'ATTEMPT_QUESTION_INVALID'
  | 'ATTEMPT_NOT_COMPLETED'
  | 'ATTEMPT_ANSWER_NOT_FOUND'
  /** AUTH module — 15 codes */
  | 'AUTH_INVALID_CREDENTIALS'
  | 'AUTH_INVALID_REFRESH_TOKEN'
  | 'AUTH_TOKEN_REUSED'
  | 'AUTH_SESSION_CONTEXT_MISMATCH'
  | 'AUTH_USER_NOT_FOUND'
  | 'AUTH_RATE_LIMITED'
  | 'AUTH_RESOURCE_CONFLICT'
  | 'AUTH_SESSION_NOT_FOUND'
  | 'AUTH_INVALID_TOKEN'
  | 'AUTH_INVALID_CURRENT_PASSWORD'
  | 'AUTH_DELETION_FAILED'
  | 'AUTH_PASSWORD_REUSE'
  | 'AUTH_OAUTH_INVALID_TOKEN'
  | 'AUTH_OAUTH_ACCOUNT_ALREADY_EXISTS'
  | 'AUTH_OAUTH_LINKING_REQUIRED'
  /** BADGE module — 1 codes */
  | 'BADGE_NOT_FOUND'
  /** BOOKMARK module — 4 codes */
  | 'BOOKMARK_NOT_FOUND'
  | 'BOOKMARK_COLLECTION_NOT_FOUND'
  | 'BOOKMARK_CONFLICT'
  | 'BOOKMARK_VALIDATION'
  /** CATEGORY module — 6 codes */
  | 'CATEGORY_NOT_FOUND'
  | 'CATEGORY_FOLLOW_NOT_FOUND'
  | 'CATEGORY_ANALYTICS_NOT_FOUND'
  | 'CATEGORY_SLUG_CONFLICT'
  | 'CATEGORY_ALREADY_ACTIVE'
  | 'CATEGORY_RESTORE_INVARIANT'
  /** COLLECTION module — 2 codes */
  | 'COLLECTION_FORBIDDEN'
  | 'COLLECTION_CONFLICT'
  /** COMMENT module — 10 codes */
  | 'COMMENT_NOT_FOUND'
  | 'COMMENT_QUIZ_NOT_FOUND'
  | 'COMMENT_REPORT_NOT_FOUND'
  | 'COMMENT_FORBIDDEN'
  | 'COMMENT_SELF_VOTE'
  | 'COMMENT_SELF_REPORT'
  | 'COMMENT_MODERATOR_REQUIRED'
  | 'COMMENT_REPLY_LIMIT_EXCEEDED'
  | 'COMMENT_DUPLICATE_REPORT'
  | 'COMMENT_PARENT_COMMENT_CROSS_THREAD'
  /** INSTANCE module — 10 codes */
  | 'INSTANCE_NOT_FOUND'
  | 'INSTANCE_NOT_HOST'
  | 'INSTANCE_NOT_OPEN'
  | 'INSTANCE_FULL'
  | 'INSTANCE_ALREADY_STARTED'
  | 'INSTANCE_ALREADY_CLOSED'
  | 'INSTANCE_ALREADY_FINISHED'
  | 'INSTANCE_OPTIMISTIC_LOCK'
  | 'INSTANCE_NOT_IN_COUNTDOWN'
  | 'INSTANCE_COUNTDOWN_ALREADY_STARTED'
  /** MIN module — 1 codes */
  | 'MIN_PLAYERS_NOT_MET'
  /** NOTIFICATION module — 2 codes */
  | 'NOTIFICATION_NOT_FOUND'
  | 'NOTIFICATION_FORBIDDEN'
  /** PLAYER module — 1 codes */
  | 'PLAYER_ALREADY_JOINED'
  /** QUIZ module — 14 codes */
  | 'QUIZ_OPERATION_FAILED'
  | 'QUIZ_NOT_FOUND'
  | 'QUIZ_FORBIDDEN'
  | 'QUIZ_SLUG_CONFLICT'
  | 'QUIZ_CONFLICT'
  | 'QUIZ_VALIDATION_FAILED'
  | 'QUIZ_VERSION_IMMUTABLE'
  | 'QUIZ_VERSION_NOT_FOUND'
  | 'QUIZ_INSUFFICIENT_QUESTIONS'
  | 'QUIZ_QUESTION_POSITION_CONFLICT'
  | 'QUIZ_ANSWER_OPTION_POSITION_CONFLICT'
  | 'QUIZ_MULTIPLE_CORRECT_OPTIONS'
  | 'QUIZ_ANALYTICS_NOT_FOUND'
  | 'QUIZ_ANALYTICS_CALCULATION_FAILED'
  /** RANKING module — 3 codes */
  | 'RANKING_INVALID_XP_EVENT'
  | 'RANKING_RANK_CALCULATION_ERROR'
  | 'RANKING_PERIOD_RESET_ERROR'
  /** REVIEW module — 6 codes */
  | 'REVIEW_NOT_FOUND'
  | 'REVIEW_FORBIDDEN'
  | 'REVIEW_CONFLICT'
  | 'REVIEW_ALREADY_REPORTED'
  | 'REVIEW_VALIDATION'
  | 'REVIEW_ATTEMPT_REQUIRED'
  /** SOCIAL module — 11 codes */
  | 'SOCIAL_FRIEND_REQUEST_NOT_FOUND'
  | 'SOCIAL_FRIEND_REQUEST_FORBIDDEN'
  | 'SOCIAL_FRIEND_LIST_FORBIDDEN'
  | 'SOCIAL_SELF_FRIEND_REQUEST'
  | 'SOCIAL_ALREADY_FRIENDS'
  | 'SOCIAL_BLOCKED_USER'
  | 'SOCIAL_USER_BLOCKED'
  | 'SOCIAL_PENDING_REQUEST_EXISTS'
  | 'SOCIAL_FRIENDSHIP_NOT_FOUND'
  | 'SOCIAL_USER_NOT_BLOCKED'
  | 'SOCIAL_FOLLOW_NOT_FOUND'
  /** TAG module — 5 codes */
  | 'TAG_NOT_FOUND'
  | 'TAG_ANALYTICS_NOT_FOUND'
  | 'TAG_SLUG_CONFLICT'
  | 'TAG_ALREADY_ACTIVE'
  | 'TAG_RESTORE_INVARIANT'
  /** TOURNAMENT module — 15 codes */
  | 'TOURNAMENT_NOT_FOUND'
  | 'TOURNAMENT_ROUND_NOT_FOUND'
  | 'TOURNAMENT_NOT_REGISTERED'
  | 'TOURNAMENT_FORBIDDEN'
  | 'TOURNAMENT_CONFLICT'
  | 'TOURNAMENT_ALREADY_REGISTERED'
  | 'TOURNAMENT_ATTEMPT_ALREADY_EXISTS'
  | 'TOURNAMENT_PARTICIPANT_STATE'
  | 'TOURNAMENT_ALREADY_WITHDRAWN'
  | 'TOURNAMENT_VALIDATION'
  | 'TOURNAMENT_REGISTRATION_CLOSED'
  | 'TOURNAMENT_FULL'
  | 'TOURNAMENT_ROUND_NOT_OPEN'
  | 'TOURNAMENT_UNREGISTER_CLOSED'
  | 'TOURNAMENT_WITHDRAW_CLOSED'
  /** USER module — 4 codes */
  | 'USER_NOT_FOUND'
  | 'USER_ANALYTICS_NOT_FOUND'
  | 'USER_PROFILE_PRIVATE'
  | 'USER_BADGE_OWNERSHIP_NOT_FOUND'
  /** Synthesized GLOBAL_* codes for native HttpException paths (RFC 7807 §8.5) */
  | 'GLOBAL_BAD_REQUEST' /** 400 */
  | 'GLOBAL_VALIDATION_FAILED' /** 400 (string[] ValidationPipe) */
  | 'GLOBAL_UNAUTHENTICATED' /** 401 */
  | 'GLOBAL_FORBIDDEN' /** 403 */
  | 'GLOBAL_NOT_FOUND' /** 404 */
  | 'GLOBAL_METHOD_NOT_ALLOWED' /** 405 */
  | 'GLOBAL_CONFLICT' /** 409 */
  | 'GLOBAL_UNPROCESSABLE' /** 422 */
  | 'GLOBAL_RATE_LIMITED' /** 429 */
  | 'GLOBAL_INTERNAL_ERROR' /** 5xx */;

export const KNOWN_ERROR_CODES = [
  // ACHIEVEMENT
  'ACHIEVEMENT_USER_NOT_FOUND',
  'ACHIEVEMENT_GRANT_ERROR',
  // ATTEMPT
  'ATTEMPT_NOT_FOUND',
  'ATTEMPT_FORBIDDEN',
  'ATTEMPT_VALIDATION_FAILED',
  'ATTEMPT_ALREADY_STARTED',
  'ATTEMPT_NOT_ACTIVE',
  'ATTEMPT_QUESTION_ALREADY_ANSWERED',
  'ATTEMPT_QUIZ_NOT_PUBLISHED',
  'ATTEMPT_QUESTION_INVALID',
  'ATTEMPT_NOT_COMPLETED',
  'ATTEMPT_ANSWER_NOT_FOUND',
  // AUTH
  'AUTH_INVALID_CREDENTIALS',
  'AUTH_INVALID_REFRESH_TOKEN',
  'AUTH_TOKEN_REUSED',
  'AUTH_SESSION_CONTEXT_MISMATCH',
  'AUTH_USER_NOT_FOUND',
  'AUTH_RATE_LIMITED',
  'AUTH_RESOURCE_CONFLICT',
  'AUTH_SESSION_NOT_FOUND',
  'AUTH_INVALID_TOKEN',
  'AUTH_INVALID_CURRENT_PASSWORD',
  'AUTH_DELETION_FAILED',
  'AUTH_PASSWORD_REUSE',
  'AUTH_OAUTH_INVALID_TOKEN',
  'AUTH_OAUTH_ACCOUNT_ALREADY_EXISTS',
  'AUTH_OAUTH_LINKING_REQUIRED',
  // BADGE
  'BADGE_NOT_FOUND',
  // BOOKMARK
  'BOOKMARK_NOT_FOUND',
  'BOOKMARK_COLLECTION_NOT_FOUND',
  'BOOKMARK_CONFLICT',
  'BOOKMARK_VALIDATION',
  // CATEGORY
  'CATEGORY_NOT_FOUND',
  'CATEGORY_FOLLOW_NOT_FOUND',
  'CATEGORY_ANALYTICS_NOT_FOUND',
  'CATEGORY_SLUG_CONFLICT',
  'CATEGORY_ALREADY_ACTIVE',
  'CATEGORY_RESTORE_INVARIANT',
  // COLLECTION
  'COLLECTION_FORBIDDEN',
  'COLLECTION_CONFLICT',
  // COMMENT
  'COMMENT_NOT_FOUND',
  'COMMENT_QUIZ_NOT_FOUND',
  'COMMENT_REPORT_NOT_FOUND',
  'COMMENT_FORBIDDEN',
  'COMMENT_SELF_VOTE',
  'COMMENT_SELF_REPORT',
  'COMMENT_MODERATOR_REQUIRED',
  'COMMENT_REPLY_LIMIT_EXCEEDED',
  'COMMENT_DUPLICATE_REPORT',
  'COMMENT_PARENT_COMMENT_CROSS_THREAD',
  // INSTANCE
  'INSTANCE_NOT_FOUND',
  'INSTANCE_NOT_HOST',
  'INSTANCE_NOT_OPEN',
  'INSTANCE_FULL',
  'INSTANCE_ALREADY_STARTED',
  'INSTANCE_ALREADY_CLOSED',
  'INSTANCE_ALREADY_FINISHED',
  'INSTANCE_OPTIMISTIC_LOCK',
  'INSTANCE_NOT_IN_COUNTDOWN',
  'INSTANCE_COUNTDOWN_ALREADY_STARTED',
  // MIN
  'MIN_PLAYERS_NOT_MET',
  // NOTIFICATION
  'NOTIFICATION_NOT_FOUND',
  'NOTIFICATION_FORBIDDEN',
  // PLAYER
  'PLAYER_ALREADY_JOINED',
  // QUIZ
  'QUIZ_OPERATION_FAILED',
  'QUIZ_NOT_FOUND',
  'QUIZ_FORBIDDEN',
  'QUIZ_SLUG_CONFLICT',
  'QUIZ_CONFLICT',
  'QUIZ_VALIDATION_FAILED',
  'QUIZ_VERSION_IMMUTABLE',
  'QUIZ_VERSION_NOT_FOUND',
  'QUIZ_INSUFFICIENT_QUESTIONS',
  'QUIZ_QUESTION_POSITION_CONFLICT',
  'QUIZ_ANSWER_OPTION_POSITION_CONFLICT',
  'QUIZ_MULTIPLE_CORRECT_OPTIONS',
  'QUIZ_ANALYTICS_NOT_FOUND',
  'QUIZ_ANALYTICS_CALCULATION_FAILED',
  // RANKING
  'RANKING_INVALID_XP_EVENT',
  'RANKING_RANK_CALCULATION_ERROR',
  'RANKING_PERIOD_RESET_ERROR',
  // REVIEW
  'REVIEW_NOT_FOUND',
  'REVIEW_FORBIDDEN',
  'REVIEW_CONFLICT',
  'REVIEW_ALREADY_REPORTED',
  'REVIEW_VALIDATION',
  'REVIEW_ATTEMPT_REQUIRED',
  // SOCIAL
  'SOCIAL_FRIEND_REQUEST_NOT_FOUND',
  'SOCIAL_FRIEND_REQUEST_FORBIDDEN',
  'SOCIAL_FRIEND_LIST_FORBIDDEN',
  'SOCIAL_SELF_FRIEND_REQUEST',
  'SOCIAL_ALREADY_FRIENDS',
  'SOCIAL_BLOCKED_USER',
  'SOCIAL_USER_BLOCKED',
  'SOCIAL_PENDING_REQUEST_EXISTS',
  'SOCIAL_FRIENDSHIP_NOT_FOUND',
  'SOCIAL_USER_NOT_BLOCKED',
  'SOCIAL_FOLLOW_NOT_FOUND',
  // TAG
  'TAG_NOT_FOUND',
  'TAG_ANALYTICS_NOT_FOUND',
  'TAG_SLUG_CONFLICT',
  'TAG_ALREADY_ACTIVE',
  'TAG_RESTORE_INVARIANT',
  // TOURNAMENT
  'TOURNAMENT_NOT_FOUND',
  'TOURNAMENT_ROUND_NOT_FOUND',
  'TOURNAMENT_NOT_REGISTERED',
  'TOURNAMENT_FORBIDDEN',
  'TOURNAMENT_CONFLICT',
  'TOURNAMENT_ALREADY_REGISTERED',
  'TOURNAMENT_ATTEMPT_ALREADY_EXISTS',
  'TOURNAMENT_PARTICIPANT_STATE',
  'TOURNAMENT_ALREADY_WITHDRAWN',
  'TOURNAMENT_VALIDATION',
  'TOURNAMENT_REGISTRATION_CLOSED',
  'TOURNAMENT_FULL',
  'TOURNAMENT_ROUND_NOT_OPEN',
  'TOURNAMENT_UNREGISTER_CLOSED',
  'TOURNAMENT_WITHDRAW_CLOSED',
  // USER
  'USER_NOT_FOUND',
  'USER_ANALYTICS_NOT_FOUND',
  'USER_PROFILE_PRIVATE',
  'USER_BADGE_OWNERSHIP_NOT_FOUND',
  // Synthesized GLOBAL_* codes
  'GLOBAL_BAD_REQUEST',
  'GLOBAL_VALIDATION_FAILED',
  'GLOBAL_UNAUTHENTICATED',
  'GLOBAL_FORBIDDEN',
  'GLOBAL_NOT_FOUND',
  'GLOBAL_METHOD_NOT_ALLOWED',
  'GLOBAL_CONFLICT',
  'GLOBAL_UNPROCESSABLE',
  'GLOBAL_RATE_LIMITED',
  'GLOBAL_INTERNAL_ERROR',
] as const satisfies readonly ErrorCode[];

export const SYNTHESIZED_ERROR_CODES = [
  'GLOBAL_BAD_REQUEST',  // 400
  'GLOBAL_VALIDATION_FAILED',  // 400 (string[] ValidationPipe)
  'GLOBAL_UNAUTHENTICATED',  // 401
  'GLOBAL_FORBIDDEN',  // 403
  'GLOBAL_NOT_FOUND',  // 404
  'GLOBAL_METHOD_NOT_ALLOWED',  // 405
  'GLOBAL_CONFLICT',  // 409
  'GLOBAL_UNPROCESSABLE',  // 422
  'GLOBAL_RATE_LIMITED',  // 429
  'GLOBAL_INTERNAL_ERROR',  // 5xx
] as const;

export function isKnownErrorCode(code: string): code is ErrorCode {
  return (KNOWN_ERROR_CODES as readonly string[]).includes(code);
}
