/**
 * Public API surface barrel.
 *
 * Consumers must import HTTP concerns from this file — never from
 * `./core` directly, and never from `axios` directly. The barrel is the
 * single source of truth for everything HTTP-related on the frontend.
 *
 * Exempt from the `no-restricted-imports` rule for `axios`:
 *   - See `eslint.config.mjs` and Epic 1.2 / TKT-1.2.1.4.
 *   - Only this directory (`src/lib/api/**`) is allowed to depend on `axios`.
 *
 * What this barrel owns:
 *   - `customInstance`, `authOnlyInstance`: the two axios instances with
 *     envelope unwrapping, refresh-on-401, cross-tab sync, and RFC 7807
 *     error decoding. Added in Epic 1.4.
 *   - `ApiError`, `isApiError`, `ApiErrorData`: the typed error class.
 *     Rich getters (code, detail, requestId, …) added in Epic 1.3.
 *   - `CustomConfig`: the request-config augmentation type.
 *   - `orvalCustomInstance`: the orval mutator that the generated SDK
 *     calls into. Regenerated by `pnpm generate:api` (Epic 1.1).
 *   - Per-tag SDK builders (`getAuth`, `getUsers`, …) re-exported from
 *     `./generated/<tag>/<tag>`. Regenerated by `pnpm generate:api`.
 *     See TKT-1.2.1.2.
 *
 * Re-export style (decided in TKT-1.2.1.2):
 *   - Per-tag, named re-exports (one `export { get<Tag> } from './generated/<tag>/<tag>'` per tag).
 *     Rationale: gives the bundler a single named-export per tag (better
 *     tree-shaking than `export *`), and avoids the name-collision risk
 *     of `export *` when two tags both export the same type name (e.g.
 *     `LoginResponseDto`).
 *   - The schemas barrel is re-exported as `*` because the underlying
 *     DTOs are flat (no name collisions) and consumers typically need
 *     many at once.
 *
 * Source ticket: TKT-1.2.1.1 + TKT-1.2.1.2
 * Parent epic:   Epic 1.2 (SDK Regeneration & Barrel Consolidation)
 */

export { customInstance } from './core/custom-instance';
export { authOnlyInstance } from './core/auth-only-instance';
export { orvalCustomInstance } from './core/custom-instance';

export { ApiError, isApiError } from './core/ApiError';
export type { ApiErrorData } from './core/ApiError';
export type { CustomConfig } from './core/custom-instance';

// `coerceToApiError` — Phase-3 canonical entry point for turning an
// `unknown` thrown value into a typed `ApiError`. Replaces the
// per-feature `wrapAsApiError` / `makeSyntheticError` helpers.
// Re-exported from the public barrel so application code can
// `import { coerceToApiError } from '@/lib/api'`.
export { coerceToApiError } from './error-coercion';
export type { ApiErrorInput } from './error-types';

// Cursor pagination primitive (Epic 3.2). Pure helper used by
// `useCursorPaginated` to deduplicate cross-page items when a cursor's
// next page overlaps with the previous page (rare; cache-invalidation
// edge case). Re-exported here so consumers (the hook, the hook's tests,
// and any future feature) can import it from the public barrel without
// reaching into `src/lib/api/append-unique-by-id.ts` directly.
export { appendUniqueById } from './append-unique-by-id';

// `useCursorPaginated` — Phase-3 cursor-pagination primitive (Epic 3.2).
// The hook wraps `useSWRInfinite`, dedupes cross-page items via
// `appendUniqueById`, and surfaces a stable
// `UseCursorPaginatedResult<T>` shape. Public contract types are
// re-exported too so consumers can import them from the public barrel
// without reaching into `./use-cursor-paginated.types.ts` directly.
export {
    useCursorPaginated
} from './use-cursor-paginated'
export type {
  CursorFetcher,
  CursorFetcherArgs,
  CursorPage,
  CursorPageFallbackData,
  CursorParams,
  OffsetFetcher,
  OffsetFetcherArgs,
    OffsetPage,
  OffsetPageFallbackData,
  OffsetParams,
  PaginationKind,
  UseCursorPaginatedDefaultParams,
  UseCursorPaginatedParams,
  UseCursorPaginatedResult
} from './use-cursor-paginated.types'

// TKT-7.5 cleanup, Phase 5 / P0-20 — strict runtime guards for
// `CursorPage<T>` and `OffsetPage<T>`. The previous implementation
// used `Object.prototype.hasOwnProperty.call(...)` which is
// structurally loose; these guards reject malformed wire payloads
// (typed-error envelopes, axios-interceptor response wrappers) and
// surface a useful error via `assertPageShape`.
export {
  isCursorPage,
  isOffsetPage,
  isAnyCursorLikePage,
  assertPageShape,
} from './is-cursor-page'

// P1-24 cleanup, Phase 9: `ProjectWithId<T, Alias>` is a generic
// type-level helper that aliases any non-`id` primary-key field on a
// DTO (`userId`, `quizId`, `categoryId`, …) as `id` so the item is
// usable with `appendUniqueById`, `useCursorPaginated`, and other
// `T extends { id: string }`-constrained primitives without a
// hand-rolled mapping layer.
export {
  type ProjectWithId,
  projectWithId,
} from './project-with-id'

// `useOffsetPaginated` — Phase-6 offset-aware pagination primitive
// (Epic 6.9 / TKT-6.9.D1). The hook wraps `useCursorPaginated` with
// `paginationKind: 'offset'` and exposes an offset-numbered API
// surface (`offset` / `limit` / `hasMore` / `loadMore`). Public
// contract types are re-exported so consumers can import them from
// the public barrel.
export {
  useOffsetPaginated,
  FEED_DEFAULT_LIMIT,
  FEED_MAX_LIMIT,
} from './use-offset-paginated'
export type {
  OffsetPaginatedFetcher,
  UseOffsetPaginatedParams,
  UseOffsetPaginatedResult,
} from './use-offset-paginated'

// `useSingleWithRetry` — Phase-3 single-resource read primitive (Epic 3.6).
// The hook shares the 429 backoff policy with `useCursorPaginated`
// (250 / 500 / 1000 ms), exposes a manual `retry()` action, and
// performs no quiz-specific 404 mapping. Public contract types are
// re-exported so consumers can import them from the public barrel.
export {
  useSingleWithRetry
} from './use-single-with-retry'
export type {
  SingleFetcher,
  UseSingleWithRetryParams,
  UseSingleWithRetryResult
} from './use-single-with-retry'

// `useOptimisticToggle` — Phase-3 follow / unfollow mutation primitive
// (Story 3.9 / TKT-3.9.B1). The generic hook enforces the
// 500 ms cooldown, the optimistic update + rollback discipline, the
// SWR cache invalidation policy, and the error taxonomy. Reused by
// Story 3.10's bookmark surface.
export {
  useOptimisticToggle,
  classifyOptimisticToggleError
} from './useOptimisticToggle'
export type {
  OptimisticToggleError,
  OptimisticToggleErrorKind,
  OptimisticToggleStatus,
  OptimisticToggleSWRKey,
  UseOptimisticToggleParams,
  UseOptimisticToggleResult
} from './useOptimisticToggle'

// TKT-7.5 cleanup, Phase 6: `useOptimisticMutation` (Phase 4 /
// TKT-4.1.E1) is the canonical typed-confirm + cross-tab-broadcast
// superset of `useOptimisticToggle`. Per-feature hooks
// (`useFollow` / `useUnfollow` / `useBlock` / `useSendFriendRequest`
// / `useRespondFriendRequest` / `useHideComment` / etc.) now
// delegate to this primitive instead of hand-rolling snapshot +
// revert + cooldown + revalidation inline.
export {
  useOptimisticMutation,
  COOLDOWN_RESULT,
  isApiErrorRejection,
} from './useOptimisticMutation'
export type {
  OptimisticMutationBroadcast,
  OptimisticMutationCall,
  OptimisticMutationConfirm,
  OptimisticMutationPatcher,
  OptimisticMutationResult,
  OptimisticMutationRun,
  OptimisticMutationStatus,
  OptimisticMutationSWRKey,
  UseOptimisticMutationResult,
} from './useOptimisticMutation'

// ─── Per-tag SDK builders ────────────────────────────────────────────────
// Regenerated by `pnpm generate:api`. If a new tag directory appears under
// `./generated/` (because the backend added a new controller), add the
// corresponding `export { get<NewTag> } from './generated/<new-tag>/<new-tag>'`
// line here. Keep this list in alphabetical order.
//
// Tag inventory at planning time:
//   attempts, auth, bookmarks, categories, instances, quizzes, reviews,
//   tags, tournaments, users  (10 tags — see docs/api-codegen.md for the
// mapping to backend controllers).
//
// Tags named in the parent ticket that do NOT exist on disk at this commit:
//   discussions, health, leaderboard, notification.
// They are not in `./generated/`, so they are not re-exported here. They
// will appear automatically when the backend exposes the matching
// controllers and `pnpm generate:api` is run.
//
// TKT-6.1.E1 — `getSocial` was added with the Phase 6 SDK regeneration.
// Social controllers (`SocialController`) now exist and ship a stable
// social SDK surface.
export { getSocial } from './generated/social/social';

export { getAttempts } from './generated/attempts/attempts';
export { getAuth } from './generated/auth/auth';
export { getBookmarks } from './generated/bookmarks/bookmarks';
export { getCategories } from './generated/categories/categories';
export { getComments } from './generated/comments/comments';
export { getInstances } from './generated/instances/instances';
export { getLeaderboards } from './generated/leaderboards/leaderboards';
export { getAchievements } from './generated/achievements/achievements';
export { getNotifications } from './generated/notifications/notifications';
export { getSearch } from './generated/search/search';
export { getQuizzes } from './generated/quizzes/quizzes';
export { getReviews } from './generated/reviews/reviews';
export { getTags } from './generated/tags/tags';
export { getTournaments } from './generated/tournaments/tournaments';
export { getUsers } from './generated/users/users';

// ─── Generated DTOs ──────────────────────────────────────────────────────
// All request/response DTOs are re-exported via `*`. Consumers typically
// destructure many at once, so per-DTO re-exports would be noisier than
// helpful.
export * from './generated/schemas';