'use client'

import { useEffect } from 'react'

export function PwaServiceWorker() {
  useEffect(() => {
    if (!('serviceWorker' in navigator)) return

    if (process.env.NODE_ENV !== 'production') {
      navigator.serviceWorker.getRegistrations().then((registrations) => {
        registrations.forEach((registration) => {
          void registration.unregister()
        })
      })
      return
    }

    // sw.js is generated by Next.js PWA plugin at build time.
    // If it is missing, skip silently rather than crashing.
    navigator.serviceWorker.register('/sw.js').catch(() => {
      // ignore in environments where sw.js is not yet generated
    })
  }, [])

  return null
}
