/**
 * `features/admin/comment-moderation/admin-comment-report-types.ts`
 *
 * Source epic:   Epic 7.6 — Comment Moderation (Hide, Restore, and Report Queue).
 * Source ticket: TKT-7.6.B1.
 *
 * ## Purpose
 *
 * Local type surface for the comment-moderation queue. Every hook,
 * component, and mutation in `features/admin/comment-moderation/**`
 * imports its DTOs from this module instead of reaching into
 * `@/lib/api/generated/schemas` directly. The module is the single
 * source of truth for the queue's typed surface; future migrations
 * (e.g. a backend `status` rename) only need to update this file.
 *
 * ## Source-of-truth rule
 *
 * The local types below are direct aliases for the regenerated SDK
 * types in `lib/api/generated/schemas`. The SDK is regenerated by
 * orval from the backend OpenAPI spec, so when the backend changes
 * the SDK regeneration cascades and this module's aliases shift with
 * it. The local module exists to:
 *
 *   1. Pin the queue-side type surface (the queue does not need to
 *      re-export every SDK DTO).
 *   2. Define the SWR page shape (`CommentReportListDto`) that the
 *      queue's hook layer produces from the SDK response.
 *   3. Encode the documented page size
 *      (`COMMENT_REPORTS_PAGE_SIZE`).
 *   4. Document the comment-side hide / restore request DTOs so
 *      consumers do not need to import them from the service module.
 *
 * ## Authoritative source rule
 *
 * The evidence file `EPIC_7_6_A1.md` records the contract fact that
 * the regenerated SDK is the source of truth — see §5 for the verbatim
 * `CommentReportListDto` cursor-pagination contract and the four
 * endpoint shapes. Any disagreement between this module and the SDK
 * is resolved by the SDK.
 *
 * ## Cross-batch invariants
 *
 * - The `status` union mirrors `ReportDtoStatus` (the SDK's
 *   `reviewed | dismissed | actioned | open` set); the `state`
 *   discriminated union below aliases the SDK union 1:1.
 * - `ReportActionDto` is the SDK-generated `ReviewReportDto` (the
 *   action payload), reused from
 *   `features/admin/services/comment-moderation.service.ts`. The
 *   queue never re-defines this; it never narrows the union beyond
 *   what the SDK exposes.
 * - The SWR page type matches the service wrapper's
 *   `CommentReportsPage` (TKT-7.1.E4) exactly.
 * - `CommentHideRequestDto` and `CommentRestoreRequestDto` are
 *   re-exported from `comment-moderation.service.ts` (TKT-7.1.E4);
 *   this module does not redefine them.
 */

import type {
  ReportDto,
  ReportDtoStatus,
  ReviewReportDto,
  ReviewReportDtoStatus,
} from '@/lib/api/generated/schemas';

import type {
  CommentHideRequestDto,
  CommentReportsPage,
  CommentRestoreRequestDto,
} from '@/features/admin/services/comment-moderation.service';

// ─── State / action unions ──────────────────────────────────────────────────

/**
 * Documented lifecycle status for a comment-report row. Mirrors the
 * SDK's `ReportDtoStatus` union:
 *
 *   - `'open'`      — newly filed, awaiting moderation action.
 *   - `'reviewed'`  — acknowledged; no override taken.
 *   - `'dismissed'` — closed without action.
 *   - `'actioned'`  — closed with action taken (hide / delete).
 *
 * The 2-state `pending` / `resolved` vocabulary the high-level story
 * uses is the *queue* filter, not the SDK contract; the queue
 * surfaces a `pending` / `resolved` `?show=` URL filter that maps
 * server-side to `status: 'open'` and the three resolved statuses
 * respectively.
 */
export type CommentReportState = ReportDtoStatus;

export const COMMENT_REPORT_STATES = Object.freeze({
  open: 'open',
  reviewed: 'reviewed',
  dismissed: 'dismissed',
  actioned: 'actioned',
} as const);

/**
 * Documented SDK action values accepted by
 * `PATCH /api/v1/admin/comments/reports/:reportId`. The payload shape
 * is `ReviewReportDto` (re-exported from `comment-moderation.service`).
 *
 * The union is **the SDK contract**, not a custom alias.
 */
export type CommentReportAction = ReviewReportDtoStatus;

export const COMMENT_REPORT_ACTIONS_SDK = Object.freeze({
  reviewed: 'reviewed',
  dismissed: 'dismissed',
  actioned: 'actioned',
} as const) satisfies Readonly<Record<CommentReportAction, CommentReportAction>>;

/**
 * Action payload sent on `PATCH` of a comment report. Mirrors
 * `ReviewReportDto` (the SDK type) — the same shape is reused by
 * both reviews and comments at the SDK level.
 */
export type CommentReportActionPayload = ReviewReportDto;

// ─── DTO aliases ────────────────────────────────────────────────────────────

/**
 * Local alias for the SDK row DTO. The queue treats this as the
 * canonical "comment report row" shape; components consume
 * `CommentReportDto` instead of the SDK-generated `ReportDto` so
 * future shape evolution (e.g. adding a `commentSnapshot` field)
 * stays additive.
 */
export type CommentReportDto = ReportDto;

// ─── SWR page shape ─────────────────────────────────────────────────────────

/**
 * SWR page shape consumed by the queue's hook layer. The shape is the
 * service wrapper's `CommentReportsPage` (TKT-7.1.E4) — a structural
 * type with `items`, `hasNextPage`, and `nextCursor` fields. The
 * queue surfaces this type under the comment-side alias so consumers
 * import the shape from a single module without depending on the
 * service path. Future migrations (e.g. a backend pagination rename)
 * only need to update the service module.
 *
 * The type is declared as a type alias (rather than an interface)
 * so the `Identifier[name='nextCursor']` AST selector does not flag
 * a redundant field declaration in this module. The field is
 * declared by `CommentReportsPage`, which is the fetcher adapter at
 * the SDK boundary (and is itself allow-listed by the Epic 3.2
 * cursor-pagination lockdown rule).
 */
export type CommentReportListDto = CommentReportsPage;

/** Re-export so the SWR page shape is the single import surface. */
export type { CommentReportsPage };

// ─── Page size ──────────────────────────────────────────────────────────────

/**
 * Documented page-size default. The SDK caps `limit` at 100; the
 * queue ships with a 20-row default so the row list fits within the
 * documented viewport without forcing the consumer to paginate
 * aggressively during dev. Callers can override this constant when
 * the queue wants a different size — the SDK caps are the only
 * runtime constraint.
 */
export const COMMENT_REPORTS_PAGE_SIZE = 20;

// ─── Hide / restore request DTOs ────────────────────────────────────────────

/**
 * Re-export the comment-hide request DTO from the service wrapper.
 * The body is optional; callers may pass `{ reason?: string }` for
 * audit-trail purposes. The current SDK call
 * (`hideComment(commentId)`) is parameterless, so the reason is
 * accepted by the service wrapper and may be silently dropped on
 * the wire until the SDK surfaces a typed body.
 */
export type { CommentHideRequestDto, CommentRestoreRequestDto };

// ─── Show filter ────────────────────────────────────────────────────────────

/**
 * Documented URL search-param values for the queue's resolved-vs-
 * pending toggle.
 *
 *   - `'pending'`   — list only `status: 'open'` reports (the
 *                    documented default).
 *   - `'resolved'`  — widen the list to include the three resolved
 *                    statuses (`reviewed`, `dismissed`, `actioned`).
 *
 * Invalid `?show=` values fall back to `'pending'` (TKT-7.6.C1).
 */
export type CommentReportShowFilter = 'pending' | 'resolved';

export const COMMENT_REPORT_SHOW_FILTERS = Object.freeze({
  pending: 'pending',
  resolved: 'resolved',
} as const) satisfies Readonly<
  Record<CommentReportShowFilter, CommentReportShowFilter>
>;

export const DEFAULT_COMMENT_REPORT_SHOW_FILTER: CommentReportShowFilter =
  'pending';

// ─── Type guards & exhaustive helper ────────────────────────────────────────

/**
 * Exhaustive check: every documented status is reachable from the
 * discriminated union, and the union does not leak non-documents.
 * Used by `__tests__/admin-comment-report-types.spec.ts` to assert
 * the structural invariant at compile time.
 *
 * @internal — exported only for the co-located spec; not consumed by
 * production code.
 */
export function assertCommentReportStateExhaustive(value: never): never {
  throw new Error(
    `Unreachable state in CommentReportState: ${String(value)}`,
  );
}

/**
 * Type guard. Narrows an unknown string to the documented
 * `CommentReportState` set. Useful when reading `status` from a
 * server payload that has not yet been regenerated.
 */
export function isCommentReportState(value: unknown): value is CommentReportState {
  return (
    typeof value === 'string' &&
    (value === 'open' ||
      value === 'reviewed' ||
      value === 'dismissed' ||
      value === 'actioned')
  );
}

/**
 * Type guard. Narrows an unknown string to the documented
 * `CommentReportAction` set. Used by the action-enum module
 * (TKT-7.6.B2) and by hook callers that need to validate an action
 * string before passing it to the SDK wrapper.
 */
export function isCommentReportAction(
  value: unknown,
): value is CommentReportAction {
  return (
    typeof value === 'string' &&
    (value === 'reviewed' || value === 'dismissed' || value === 'actioned')
  );
}

/**
 * Type guard. Narrows an unknown string to the documented
 * `CommentReportShowFilter` set. Used by the queue's read-list hook
 * (TKT-7.6.C1) to validate the `?show=` URL search param.
 */
export function isCommentReportShowFilter(
  value: unknown,
): value is CommentReportShowFilter {
  return (
    typeof value === 'string' &&
    (value === 'pending' || value === 'resolved')
  );
}