/**
 * `features/admin/review-moderation/admin-report-types.ts`
 *
 * Source epic:   Epic 7.5.
 * Source ticket: TKT-7.5.B1.
 *
 * ## Purpose
 *
 * Local type surface for the review-moderation queue. Every hook,
 * component, and mutation in `features/admin/review-moderation/**`
 * imports its DTOs from this module instead of reaching into
 * `@/lib/api/generated/schemas` directly. The module is the single
 * source of truth for the queue's typed surface; future migrations
 * (e.g. a backend `state` rename) only need to update this file.
 *
 * ## Source-of-truth rule
 *
 * The local types below are direct aliases for the regenerated SDK
 * types in `lib/api/generated/schemas`. The SDK is regenerated by
 * orval from the backend OpenAPI spec, so when the backend changes
 * the SDK regeneration cascades and this module's aliases shift with
 * it. The local module exists to:
 *
 *   1. Pin the queue-side type surface (the queue does not need to
 *      re-export every SDK DTO).
 *   2. Define the SWR page shape (`AdminReportListDto`) that the
 *      queue's hook layer produces from the SDK response.
 *   3. Encode the documented page size (`REVIEW_REPORTS_PAGE_SIZE`).
 *
 * ## Authoritative source rule
 *
 * The evidence file `EPIC_7_5_A1.md` records the contract fact that
 * the regenerated SDK is the source of truth — see §3, §4, and §5 for
 * the verbatim DTO / pagination contract. Any disagreement between
 * this module and the SDK is resolved by the SDK.
 *
 * ## Cross-batch invariants
 *
 * - The `state` discriminated union covers every documented value on
 *   `PlatformReportItemDtoStatus` and only those values.
 * - `ReportActionDto` is the SDK-generated `UpdateReportStatusDto`,
 *   not a custom union. Consumers never re-define this.
 * - The SWR page type matches the service wrapper's
 *   `ReviewReportsPage` (`features/admin/services/review-moderation.service.ts`,
 *   TKT-7.1.E3) exactly.
 */

import type {
  PlatformReportItemDto,
  PlatformReportItemDtoReason,
  PlatformReportItemDtoStatus,
  UpdateReportStatusDto,
} from '@/lib/api/generated/schemas';

/**
 * Documented `state` set for a review-report row. Mirrors the SDK's
 * `PlatformReportItemDtoStatus` union and is exhaustively narrowed
 * to its runtime values:
 *
 *   - `'open'`      — newly filed, awaiting moderation action.
 *   - `'reviewed'`  — acknowledged; no override taken.
 *   - `'dismissed'` — closed without action.
 *   - `'actioned'`  — closed with action taken (hide / delete).
 *
 * The 2-state `pending` / `resolved` set mentioned in the high-level
 * story is **not** the SDK contract; the queue filters by
 * `status: 'open'` server-side and surfaces the resolved states
 * inline on each row.
 */
export type ReportState = PlatformReportItemDtoStatus;

export const REPORT_STATES = Object.freeze({
  open: 'open',
  reviewed: 'reviewed',
  dismissed: 'dismissed',
  actioned: 'actioned',
} as const);

/**
 * Report action values accepted by `PATCH /api/v1/admin/reviews/reports/:reportId`.
 *
 * Mirrors the SDK's `UpdateReportStatusDtoStatus` union:
 *
 *   - `'reviewed'`  — acknowledge the report.
 *   - `'dismissed'` — close the report without action.
 *   - `'actioned'`  — close the report with action (hide / delete).
 *
 * The `ReportAction` union is **the SDK contract**, not a custom alias.
 */
export type ReportAction = UpdateReportStatusDto['status'];

export const REPORT_ACTIONS_SDK = Object.freeze({
  reviewed: 'reviewed',
  dismissed: 'dismissed',
  actioned: 'actioned',
} as const) satisfies Readonly<Record<ReportAction, ReportAction>>;

/**
 * Closed set of report reasons surfaced to the queue. Mirrors the SDK's
 * `PlatformReportItemDtoReason` union:
 *
 *   - `'spam'`
 *   - `'harassment'`
 *   - `'inappropriate_content'`
 *   - `'misinformation'`
 *   - `'other'`
 */
export type ReportReason = PlatformReportItemDtoReason;

/**
 * Local alias for the SDK row DTO. The queue treats this as the
 * canonical "report row" shape — components consume `AdminReportDto`
 * instead of the SDK-generated `PlatformReportItemDto` so future
 * shape evolution (e.g. adding a `reviewSnapshot` field) stays
 * additive.
 */
export type AdminReportDto = PlatformReportItemDto;

/**
 * SWR page shape consumed by the queue's hook layer. Matches the
 * service wrapper's `ReviewReportsPage` (TKT-7.1.E3) exactly:
 *
 *   - `items: AdminReportDto[]`           — page rows.
 *   - `hasNextPage: boolean`              — whether more items exist.
 *   - `nextCursor: string | null`         — opaque cursor for the next page.
 */
export interface AdminReportListDto {
  items: AdminReportDto[];
  hasNextPage: boolean;
  nextCursor: string | null;
}

/**
 * Documented page-size default. The SDK caps `limit` at 100; the
 * queue ships with a 20-row default so the row list fits within
 * the documented viewport without forcing the consumer to paginate
 * aggressively during dev. Callers can override this constant when
 * the queue wants a different size — the SDK caps are the only
 * runtime constraint.
 */
export const REVIEW_REPORTS_PAGE_SIZE = 20;

/**
 * Exhaustive check: every documented state is reachable from the
 * discriminated union, and the union does not leak non-documents.
 * Used by `__tests__/admin-report-types.spec.ts` to assert the
 * structural invariant at compile time.
 *
 * @internal — exported only for the co-located spec; not consumed by
 * production code.
 */
export function assertReportStateExhaustive(value: never): never {
  throw new Error(`Unreachable state in ReportState: ${String(value)}`);
}

/**
 * Type guard. Narrows an unknown string to the documented
 * `ReportState` set. Useful when reading `status` from a server
 * payload that has not yet been regenerated.
 */
export function isReportState(value: unknown): value is ReportState {
  return (
    typeof value === 'string' &&
    (value === 'open' ||
      value === 'reviewed' ||
      value === 'dismissed' ||
      value === 'actioned')
  );
}

/**
 * Type guard. Narrows an unknown string to the documented
 * `ReportAction` set. Used by the action-enum module and by hook
 * callers that need to validate an action string before passing it
 * to the SDK wrapper.
 */
export function isReportAction(value: unknown): value is ReportAction {
  return (
    typeof value === 'string' &&
    (value === 'reviewed' || value === 'dismissed' || value === 'actioned')
  );
}

/**
 * Type guard. Narrows an unknown string to the documented
 * `ReportReason` set.
 */
export function isReportReason(value: unknown): value is ReportReason {
  return (
    typeof value === 'string' &&
    (value === 'spam' ||
      value === 'harassment' ||
      value === 'inappropriate_content' ||
      value === 'misinformation' ||
      value === 'other')
  );
}

/**
 * Documented default filter for the queue. The backend's
 * `adminReviewControllerListPlatformReports` already defaults to
 * `status: 'open'` server-side, but the queue pins the same value
 * client-side so dev environments that bypass the SDK wrapper can
 * still rely on a documented default.
 */
export const DEFAULT_REPORT_STATUS_FILTER: ReportState = 'open';