import type { QuizHistoryEntry, QuizHistoryStats } from '@/types/quizHistory'

// ── Mock Quiz History Entries ──────────────────────────────────────────────

export const quizHistoryEntries: QuizHistoryEntry[] = [
  {
    id: 'qh-001',
    quizId: 'q-101',
    quizTitle: 'World Capitals Challenge',
    category: 'Geography',
    categoryIcon: '🌍',
    difficulty: 'Medium',
    score: 85,
    totalQuestions: 20,
    correctAnswers: 17,
    timeTaken: 540,
    completedAt: '2026-02-07T10:30:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 170,
    streak: 5,
    rank: 3,
    totalParticipants: 128,
    tags: ['geography', 'capitals']
  },
  {
    id: 'qh-002',
    quizId: 'q-102',
    quizTitle: 'JavaScript Mastery',
    category: 'Technology',
    categoryIcon: '💻',
    difficulty: 'Hard',
    score: 92,
    totalQuestions: 15,
    correctAnswers: 14,
    timeTaken: 720,
    completedAt: '2026-02-06T14:15:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 280,
    streak: 4,
    rank: 1,
    totalParticipants: 95,
    tags: ['javascript', 'programming']
  },
  {
    id: 'qh-003',
    quizId: 'q-103',
    quizTitle: 'Ancient History Trivia',
    category: 'History',
    categoryIcon: '🏛️',
    difficulty: 'Easy',
    score: 70,
    totalQuestions: 10,
    correctAnswers: 7,
    timeTaken: 300,
    completedAt: '2026-02-05T09:00:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 70,
    tags: ['history', 'ancient']
  },
  {
    id: 'qh-004',
    quizId: 'q-104',
    quizTitle: 'Organic Chemistry Basics',
    category: 'Science',
    categoryIcon: '🧪',
    difficulty: 'Hard',
    score: 45,
    totalQuestions: 20,
    correctAnswers: 9,
    timeTaken: 900,
    completedAt: '2026-02-04T16:45:00Z',
    status: 'failed',
    activityType: 'completed',
    xpEarned: 45,
    tags: ['chemistry', 'science']
  },
  {
    id: 'qh-005',
    quizId: 'q-105',
    quizTitle: 'Movie Quotes Quiz',
    category: 'Entertainment',
    categoryIcon: '🎬',
    difficulty: 'Easy',
    score: 100,
    totalQuestions: 10,
    correctAnswers: 10,
    timeTaken: 180,
    completedAt: '2026-02-03T20:00:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 200,
    streak: 3,
    rank: 1,
    totalParticipants: 210,
    tags: ['movies', 'entertainment']
  },
  {
    id: 'qh-006',
    quizId: 'q-106',
    quizTitle: 'Calculus Challenge',
    category: 'Mathematics',
    categoryIcon: '📊',
    difficulty: 'Hard',
    score: 0,
    totalQuestions: 15,
    correctAnswers: 0,
    timeTaken: 120,
    completedAt: '2026-02-02T11:30:00Z',
    status: 'abandoned',
    activityType: 'abandoned',
    xpEarned: 0,
    tags: ['math', 'calculus']
  },
  {
    id: 'qh-007',
    quizId: 'q-107',
    quizTitle: 'English Literature Classics',
    category: 'Literature',
    categoryIcon: '📚',
    difficulty: 'Medium',
    score: 80,
    totalQuestions: 20,
    correctAnswers: 16,
    timeTaken: 600,
    completedAt: '2026-02-01T13:00:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 160,
    tags: ['literature', 'english']
  },
  {
    id: 'qh-008',
    quizId: 'q-108',
    quizTitle: 'Premier League Trivia',
    category: 'Sports',
    categoryIcon: '⚽',
    difficulty: 'Medium',
    score: 65,
    totalQuestions: 20,
    correctAnswers: 13,
    timeTaken: 480,
    completedAt: '2026-01-31T18:30:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 130,
    tags: ['sports', 'football']
  },
  {
    id: 'qh-009',
    quizId: 'q-109',
    quizTitle: 'Space Exploration',
    category: 'Science',
    categoryIcon: '🧪',
    difficulty: 'Medium',
    score: 55,
    totalQuestions: 15,
    correctAnswers: 8,
    timeTaken: 450,
    completedAt: '2026-01-30T10:15:00Z',
    status: 'failed',
    activityType: 'completed',
    xpEarned: 55,
    tags: ['science', 'space']
  },
  {
    id: 'qh-010',
    quizId: 'q-110',
    quizTitle: 'Pop Music 2020s',
    category: 'Entertainment',
    categoryIcon: '🎬',
    difficulty: 'Easy',
    score: 90,
    totalQuestions: 10,
    correctAnswers: 9,
    timeTaken: 200,
    completedAt: '2026-01-29T21:00:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 180,
    streak: 2,
    tags: ['music', 'pop']
  },
  {
    id: 'qh-011',
    quizId: 'q-111',
    quizTitle: 'React & Next.js',
    category: 'Technology',
    categoryIcon: '💻',
    difficulty: 'Hard',
    score: 88,
    totalQuestions: 15,
    correctAnswers: 13,
    timeTaken: 680,
    completedAt: '2026-01-28T15:00:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 260,
    rank: 2,
    totalParticipants: 75,
    tags: ['react', 'nextjs']
  },
  {
    id: 'qh-012',
    quizId: 'q-112',
    quizTitle: 'World War II Facts',
    category: 'History',
    categoryIcon: '🏛️',
    difficulty: 'Medium',
    score: 75,
    totalQuestions: 20,
    correctAnswers: 15,
    timeTaken: 560,
    completedAt: '2026-01-27T09:30:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 150,
    tags: ['history', 'ww2']
  },
  {
    id: 'qh-013',
    quizId: 'q-113',
    quizTitle: 'General Knowledge Sprint',
    category: 'General Knowledge',
    categoryIcon: '🧠',
    difficulty: 'Easy',
    score: 95,
    totalQuestions: 25,
    correctAnswers: 24,
    timeTaken: 400,
    completedAt: '2026-01-26T12:00:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 240,
    streak: 7,
    rank: 1,
    totalParticipants: 320,
    tags: ['general', 'knowledge']
  },
  {
    id: 'qh-014',
    quizId: 'q-114',
    quizTitle: 'Python Data Science',
    category: 'Technology',
    categoryIcon: '💻',
    difficulty: 'Medium',
    score: 78,
    totalQuestions: 15,
    correctAnswers: 12,
    timeTaken: 520,
    completedAt: '2026-01-25T14:30:00Z',
    status: 'passed',
    activityType: 'completed',
    xpEarned: 156,
    tags: ['python', 'data-science']
  },
  {
    id: 'qh-015',
    quizId: 'q-115',
    quizTitle: 'Art History Renaissance',
    category: 'Art',
    categoryIcon: '🎨',
    difficulty: 'Hard',
    score: 40,
    totalQuestions: 20,
    correctAnswers: 8,
    timeTaken: 800,
    completedAt: '2026-01-24T17:00:00Z',
    status: 'failed',
    activityType: 'completed',
    xpEarned: 40,
    tags: ['art', 'renaissance']
  }
]

// ── Mock Statistics ────────────────────────────────────────────────────────

export const quizHistoryStats: QuizHistoryStats = {
  totalQuizzes: 47,
  totalCorrectAnswers: 389,
  totalQuestions: 520,
  averageScore: 76,
  bestScore: 100,
  totalTimePlayed: 28800, // 8 hours
  currentStreak: 5,
  longestStreak: 12,
  totalXpEarned: 4850,
  quizzesThisWeek: 5,
  quizzesThisMonth: 15,
  categoryBreakdown: [
    {
      category: 'Technology',
      icon: '💻',
      count: 12,
      averageScore: 86,
      bestScore: 92,
      totalTime: 8400,
      color: '#8b5cf6'
    },
    {
      category: 'Science',
      icon: '🧪',
      count: 8,
      averageScore: 68,
      bestScore: 85,
      totalTime: 5400,
      color: '#3b82f6'
    },
    {
      category: 'History',
      icon: '🏛️',
      count: 7,
      averageScore: 73,
      bestScore: 80,
      totalTime: 4200,
      color: '#22c55e'
    },
    {
      category: 'Geography',
      icon: '🌍',
      count: 6,
      averageScore: 82,
      bestScore: 95,
      totalTime: 3600,
      color: '#14b8a6'
    },
    {
      category: 'Entertainment',
      icon: '🎬',
      count: 5,
      averageScore: 91,
      bestScore: 100,
      totalTime: 2400,
      color: '#f59e0b'
    },
    {
      category: 'Sports',
      icon: '⚽',
      count: 4,
      averageScore: 70,
      bestScore: 78,
      totalTime: 2000,
      color: '#ef4444'
    },
    {
      category: 'Mathematics',
      icon: '📊',
      count: 3,
      averageScore: 55,
      bestScore: 72,
      totalTime: 1800,
      color: '#6366f1'
    },
    {
      category: 'Literature',
      icon: '📚',
      count: 2,
      averageScore: 80,
      bestScore: 80,
      totalTime: 1000,
      color: '#ec4899'
    }
  ],
  difficultyBreakdown: {
    easy: { count: 14, avgScore: 89 },
    medium: { count: 20, avgScore: 76 },
    hard: { count: 13, avgScore: 62 }
  },
  weeklyActivity: [
    { day: 'Mon', quizzes: 2, avgScore: 78 },
    { day: 'Tue', quizzes: 1, avgScore: 85 },
    { day: 'Wed', quizzes: 3, avgScore: 72 },
    { day: 'Thu', quizzes: 1, avgScore: 90 },
    { day: 'Fri', quizzes: 2, avgScore: 68 },
    { day: 'Sat', quizzes: 4, avgScore: 82 },
    { day: 'Sun', quizzes: 2, avgScore: 88 }
  ],
  monthlyScoreTrend: [
    { month: 'Sep', avgScore: 62, quizCount: 5 },
    { month: 'Oct', avgScore: 68, quizCount: 8 },
    { month: 'Nov', avgScore: 71, quizCount: 7 },
    { month: 'Dec', avgScore: 74, quizCount: 6 },
    { month: 'Jan', avgScore: 78, quizCount: 12 },
    { month: 'Feb', avgScore: 82, quizCount: 5 }
  ]
}
