import {
  listQuizzes,
  getQuizzesPopular,
  getQuizzesTrending,
  getQuizzesFeatured,
  getQuizByIdOrSlug,
  getQuizStatsByIdOrSlug,
  getQuizBySlug,
  createQuiz,
  updateQuiz,
  deleteQuiz,
  createQuizVersion,
  listQuizVersions,
  updateQuizVersion,
  publishQuizVersion,
  addQuestion,
  addQuestionsBulk,
  type ListQuizzesParams,
} from '@/features/quizzes/api/quizzes.wrapper';

export {
  listQuizzes,
  getQuizzesPopular,
  getQuizzesTrending,
  getQuizzesFeatured,
  getQuizByIdOrSlug,
  getQuizStatsByIdOrSlug,
  getQuizBySlug,
  createQuiz,
  updateQuiz,
  deleteQuiz,
  createQuizVersion,
  listQuizVersions,
  updateQuizVersion,
  publishQuizVersion,
  addQuestion,
  addQuestionsBulk,
};
export type { ListQuizzesParams };
