export { AchievementsTab } from './AchievementsTab'
export { OverviewTab } from './OverviewTab'
export { QuizzesTab } from './QuizzesTab'
export { StatisticsTab } from './StatisticsTab'
export { TournamentsTab } from './TournamentsTab'
