

import {
FEED_DEFAULT_LIMIT as FEED_DEFAULT_LIMIT_FROM_PRIMITIVE,
FEED_MAX_LIMIT as FEED_MAX_LIMIT_FROM_PRIMITIVE,
} from "@/lib/api";

export const FEED_DEFAULT_LIMIT: number = FEED_DEFAULT_LIMIT_FROM_PRIMITIVE;

export const FEED_MAX_LIMIT: number = FEED_MAX_LIMIT_FROM_PRIMITIVE;

export const FEED_PAGE_SIZE: number = FEED_DEFAULT_LIMIT;